// ConversationManager: creates, lists, selects and deletes conversations,
// delegating persistence to the ConversationStore and keeping track of which
// conversation is currently active in the Chat_Interface.
// See .kiro/specs/asistente-ia-local/design.md (section "Gestor_Conversaciones /
// Almacen_Conversaciones") and requirements.md (5.3, 5.6, 5.8).

import type { ConversationStore } from "../conversation-store/ConversationStore";
import type { Conversation, Message } from "../types/models";

/**
 * ConversationManager: wraps a `ConversationStore` and adds tracking of the
 * active conversation in the Chat_Interface, including the reselection logic
 * when the active conversation is deleted (Requisito 5.8).
 */
export class ConversationManager {
  private readonly store: ConversationStore;
  private activeConversationId: string | null = null;

  constructor(store: ConversationStore) {
    this.store = store;
  }

  /**
   * Loads the list of existing conversations, sorted in descending order by
   * `lastActivityAt` (Requisito 5.3).
   */
  async loadConversations(): Promise<Conversation[]> {
    return this.store.listConversations();
  }

  /**
   * Creates a new conversation (with a unique identifier, generated by the
   * ConversationStore) and marks it as active (Requisito 5.6).
   */
  async createConversation(): Promise<Conversation> {
    const conversation = await this.store.createConversation();
    this.activeConversationId = conversation.id;
    return conversation;
  }

  /**
   * Deletes the given conversation. If it was the active conversation,
   * selects instead the remaining conversation with the most recent
   * `lastActivityAt`, or none if none remain (Requisito 5.8).
   *
   * Returns the conversation that remains active after the operation (or
   * `null` if none remains active).
   */
  async deleteConversation(conversationId: string): Promise<Conversation | null> {
    await this.store.deleteConversation(conversationId);

    if (this.activeConversationId !== conversationId) {
      // Does not affect the currently active conversation.
      return this.activeConversationId !== null
        ? await this.store.getConversation(this.activeConversationId)
        : null;
    }

    const remaining = await this.store.listConversations();
    const next = remaining.length > 0 ? remaining[0] : undefined;
    this.activeConversationId = next?.id ?? null;
    return next ?? null;
  }

  /**
   * Adds an already-built Message to an existing Conversation, delegating
   * persistence to the ConversationStore (Requisito 5.1). Direct passthrough,
   * in the same style as `importConversation`: it does not affect nor depend
   * on which conversation is currently active.
   */
  async addMessage(conversationId: string, message: Message): Promise<void> {
    await this.store.addMessage(conversationId, message);
  }

  /**
   * Persists an already fully-formed conversation (e.g. produced by
   * `parseImport()`) into the ConversationStore and marks it as active
   * (Requisito 7.3).
   */
  async importConversation(conversation: Conversation): Promise<void> {
    await this.store.importConversation(conversation);
    this.activeConversationId = conversation.id;
  }

  /** Explicitly selects a conversation as active. */
  selectConversation(conversationId: string): void {
    this.activeConversationId = conversationId;
  }

  /** Identifier of the currently active conversation, or `null`. */
  getActiveConversationId(): string | null {
    return this.activeConversationId;
  }
}
